title: My Personal Blog
author: Javier Ruiz Vázquez
email: java.rv87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a first part of my personal blog where you will learn about angular, javascript, firebase and google cloud platform

# social links
twitter_username: @_javaruiz
github_username:  javarv87

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
